Backend: Vitis
ClockPeriod: 4
ClockUncertainty: 27%
HLSConfig:
  LayerName:
    dense1:
      Precision:
        accum: auto
        bias: auto
        result: auto
        weight: auto
      ReuseFactor: 1
      Trace: false
    dense2:
      Precision:
        accum: auto
        bias: auto
        result: auto
        weight: auto
      ReuseFactor: 1
      Trace: false
    dense3:
      Precision:
        accum: auto
        bias: auto
        result: auto
        weight: auto
      ReuseFactor: 1
      Trace: false
    input_layer:
      Precision:
        result: auto
      Trace: false
    relu1:
      Precision:
        param: auto
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    relu2:
      Precision:
        param: auto
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    relu3:
      Precision:
        param: auto
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
  Model:
    BitExact: null
    BramFactor: 1000000000
    Precision:
      default: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
InputShapes:
  input_layer:
  - 8
KerasModel: !keras_model './SampleNeuralNets/Basic/keras_model.keras'
OutputDir: ./SampleNeuralNets/Basic
OutputPredictions: null
OutputShapes:
  layer7_out:
  - 8
Part: xc7z010clg400-1
ProjectName: SampleNeuralNet
Stamp: 060883a5
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
