////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995-2003 Xilinx, Inc.
// All Right Reserved.
////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 6.3.02i
//  \   \         Application : 
//  /   /         Filename : DCM_1x_2x.v
// /___/   /\     Timestamp : 11/04/2004 08:37:40
// \   \  /  \ 
//  \___\/\___\ 
//
//Command: 
//Design Name: DCM_1x_2x
//
// Module DCM_1x_2x
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
`timescale 1ns / 1ps

module DCM_1x_2x(CLKIN_IN, 
                 RST_IN, 
                 CLKIN_IBUFG_OUT, 
                 CLK0_OUT, 
                 CLK2X_OUT, 
                 LOCKED_OUT);

    input CLKIN_IN;
    input RST_IN;
   output CLKIN_IBUFG_OUT;
   output CLK0_OUT;
   output CLK2X_OUT;
   output LOCKED_OUT;
   
   wire CLKFB_IN;
   wire CLKIN_IBUFG;
   wire CLK0_BUF;
   wire CLK2X_BUF;
   wire [6:0] GND;
   wire [15:0] GND1;
   wire GND2;
   
   assign GND = 7'b0000000;
   assign GND1 = 16'b0000000000000000;
   assign GND2 = 0;
   assign CLKIN_IBUFG_OUT = CLKIN_IBUFG;
   assign CLK0_OUT = CLKFB_IN;
   IBUFG CLKIN_IBUFG_INST (.I(CLKIN_IN), 
                           .O(CLKIN_IBUFG));
   BUFG CLK0_BUFG_INST (.I(CLK0_BUF), 
                        .O(CLKFB_IN));
   BUFG CLK2X_BUFG_INST (.I(CLK2X_BUF), 
                         .O(CLK2X_OUT));
   DCM_ADV DCM_ADV_INST (.CLKFB(CLKFB_IN), 
                         .CLKIN(CLKIN_IBUFG), 
                         .DADDR(GND[6:0]), 
                         .DCLK(GND2), 
                         .DEN(GND2), 
                         .DI(GND1[15:0]), 
                         .DWE(GND2), 
                         .PSCLK(GND2), 
                         .PSEN(GND2), 
                         .PSINCDEC(GND2), 
                         .RST(RST_IN), 
                         .CLKDV(), 
                         .CLKFX(), 
                         .CLKFX180(), 
                         .CLK0(CLK0_BUF), 
                         .CLK2X(CLK2X_BUF), 
                         .CLK2X180(), 
                         .CLK90(), 
                         .CLK180(), 
                         .CLK270(), 
                         .DO(), 
                         .DRDY(), 
                         .LOCKED(LOCKED_OUT), 
                         .PSDONE());
   // synthesis attribute CLK_FEEDBACK of DCM_ADV_INST is "1X"
   // synthesis attribute CLKDV_DIVIDE of DCM_ADV_INST is "2.000000"
   // synthesis attribute CLKFX_DIVIDE of DCM_ADV_INST is "1"
   // synthesis attribute CLKFX_MULTIPLY of DCM_ADV_INST is "4"
   // synthesis attribute CLKIN_DIVIDE_BY_2 of DCM_ADV_INST is "FALSE"
   // synthesis attribute CLKIN_PERIOD of DCM_ADV_INST is "4.000000"
   // synthesis attribute CLKOUT_PHASE_SHIFT of DCM_ADV_INST is "NONE"
   // synthesis attribute DCM_PERFORMANCE_MODE of DCM_ADV_INST is "MAX_SPEED"
   // synthesis attribute DESKEW_ADJUST of DCM_ADV_INST is "SYSTEM_SYNCHRONOUS"
   // synthesis attribute DFS_FREQUENCY_MODE of DCM_ADV_INST is "HIGH"
   // synthesis attribute DLL_FREQUENCY_MODE of DCM_ADV_INST is "HIGH"
   // synthesis attribute DUTY_CYCLE_CORRECTION of DCM_ADV_INST is "TRUE"
   // synthesis attribute PHASE_SHIFT of DCM_ADV_INST is "0"
   // synthesis attribute STARTUP_WAIT of DCM_ADV_INST is "FALSE"
   // synthesis attribute FACTORY_JF of DCM_ADV_INST is "F0F0"
   // synthesis attribute DFS_OSCILLATOR_MODE of DCM_ADV_INST is "PHASE_FREQ_LOCK"
   // synopsys translate_off
   defparam DCM_ADV_INST.CLK_FEEDBACK = "1X";
   defparam DCM_ADV_INST.CLKDV_DIVIDE = 2.000000;
   defparam DCM_ADV_INST.CLKFX_DIVIDE = 1;
   defparam DCM_ADV_INST.CLKFX_MULTIPLY = 4;
   defparam DCM_ADV_INST.CLKIN_DIVIDE_BY_2 = "FALSE";
   defparam DCM_ADV_INST.CLKIN_PERIOD = 4.000000;
   defparam DCM_ADV_INST.CLKOUT_PHASE_SHIFT = "NONE";
   defparam DCM_ADV_INST.DCM_PERFORMANCE_MODE = "MAX_SPEED";
   defparam DCM_ADV_INST.DESKEW_ADJUST = "SYSTEM_SYNCHRONOUS";
   defparam DCM_ADV_INST.DFS_FREQUENCY_MODE = "HIGH";
   defparam DCM_ADV_INST.DLL_FREQUENCY_MODE = "HIGH";
   defparam DCM_ADV_INST.DUTY_CYCLE_CORRECTION = "TRUE";
   defparam DCM_ADV_INST.PHASE_SHIFT = 0;
   defparam DCM_ADV_INST.STARTUP_WAIT = "FALSE";
   defparam DCM_ADV_INST.FACTORY_JF = 16'hF0F0;
   // synopsys translate_on
endmodule
